apiVersion: v1
kind: Template
labels:
  template: thoth-result-api-deployment
  thoth: 0.1.0
metadata:
  name: thoth-result-api-deployment
  annotations:
    description: This is Thoth Core - Results API
    openshift.io/display-name: Thoth Core
    version: 0.2.0
    tags: poc,thoth,result-api,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Core Services as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: result-api
      app: thoth-core
      component: result-api
    name: result-api
    namespace: ${THOTH_MIDDLETIER_NAMESPACE}
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      service: result-api

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: result-api
      app: thoth-core
      component: result-api
    name: result-api
    namespace: ${THOTH_MIDDLETIER_NAMESPACE}
  spec:
    replicas: 1
    selector:
      service: result-api
    template:
      metadata:
        labels:
          service: result-api
      spec:
        containers:
        - name: result-api
          env:
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                key: storage-bucket-name
                name: thoth
          - name: THOTH_PERSISTENT_VOLUME_PATH
            valueFrom:
              configMapKeyRef:
                key: ceph-results-path
                name: thoth
          - name: THOTH_CEPH_HOST
            valueFrom:
              configMapKeyRef:
                key: ceph-host
                name: thoth
          - name: THOTH_CEPH_BUCKET
            valueFrom:
              configMapKeyRef:
                key: ceph-bucket-name
                name: thoth
          - name: THOTH_CEPH_BUCKET_PREFIX
            valueFrom:
              configMapKeyRef:
                key: ceph-bucket-prefix
                name: thoth
          - name: THOTH_CEPH_KEY_ID
            valueFrom:
              secretKeyRef:
                name: thoth
                key: ceph-key-id
          - name: THOTH_CEPH_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: thoth
                key: ceph-secret-key
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: '/readiness'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: '/liveness'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - result-api
        from:
          kind: ImageStreamTag
          name: 'result-api:latest'

- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: thoth-core
    name: result-api
    namespace: ${THOTH_MIDDLETIER_NAMESPACE}
  spec:
    name: latest

parameters:
- displayName: Thoth Middletier Namespace
  description: Name of the Thoth Middletier Namespace
  required: true
  name: THOTH_MIDDLETIER_NAMESPACE
